### ISSUE TITLE
通过CS内存加载的方式去执行的话有没有办法将扫描结果输出到文本里面呢?

### ISSUE THREAD

**Issue by helloyw** [k8gege/Aggressor#1]
通过CS内存加载的方式去执行的话有没有办法将扫描结果输出到文本里面呢?

**Comment by k8gege** [comment]
> 通过CS内存加载的方式去执行的话有没有办法将扫描结果输出到文本里面呢?

密码爆破会，其它模块只能CMD下重定向输出

**Comment by helloyw** [comment]
嗯好的谢谢，当一次扫描得太多CS不会显示全部。
